# Generated by Django 4.2.3 on 2023-07-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_highlighted_remove_snippet_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['created']},
        ),
    ]
